### ISSUE TITLE
feat: add builder mode when editing a modelfile

### ISSUE THREAD

**Issue by jeremiahsb** [open-webui/open-webui#187]
I know that the modelfile support is still in development, so not sure if this is a bug or a feature request. When you go into the modelfiles section and create a new modelfile, you have the option to toggle between builder mode and raw format. If you've previously created a modelfile and go back in to edit it, you don't see the option for builder mode, raw format is selected by default.

It would be nice to have the edit functionality behave like the create functionality. Not a deal breaker by any stretch, just a small quality of life improvement.

**Comment by tjbck** [comment]
Hi, It indeed is WIP at the moment, will add the builder mode to edit page as well in the near future. Stay tuned, Thanks!

**Comment by Silentoplayz** [comment]
I'm bumping this issue as it hasn't had any activity since Dec 2023. This issue is still valid for the most part, as the `Modelfile Format` option is unavailable/missing from the UI when going back to edit a previously created Modelfile. The `Builder Mode` is selected by default now, unlike what was mentioned before:
> "*you don't see the option for builder mode, raw format is selected by default.*"

This also prevents modifications to advanced model parameters (directly from the Modelfile itself) with an already created Modelfile too. That is because `Modelfile Advanced Settings` is only available in `Raw Format` mode. This isn't the main issue I'd like to point out, as yes, advanced model parameters are indeed "advanced" settings. With this being said, I am pointing out why it could still be seen as an issue that the option for switching models in an already made Modelfile is missing.

**Comment by tjbck** [comment]
PR for #665 should include this feature as well.

**Comment by tjbck** [comment]
Added to our dev branch!
