### ISSUE TITLE
Litellm not working with IBM watsonx.ai. update litellm version to 1.35.31 or higher

### ISSUE THREAD

**Issue by zuberahmed1987** [open-webui/open-webui#2520]
# Bug Report

## Description

**Bug Summary:**
the litellm provided with open webui is old and does not support IBM watsonx.ai models.
The support to IBM watsonx.ai is added in litellm in version v1.35.31 but latest open webui contains litellm version v1.35.28.
Please refer this this release https://github.com/BerriAI/litellm/releases/tag/v1.35.31

**Steps to Reproduce:**
Try to add ibm watsonx end point it gives error and does not work as it is not supported by litellm version shipped with open webui

**Expected Behavior:**
IBM watsonx.ai should also work once the litellm version will be updates to 1.35.31 or higher.

**Actual Behavior:**
IBM watsonx.ai not working with 

## Environment

- **Open WebUI Version:  0.1.125**

**Comment by justinh-rahb** [comment]
Got some bad news. The next version is going to be **v0.2.0**, and we'll be removing our built-in LiteLLM instance and UI. You'll still be able to use an external LiteLLM instance as an "OpenAI" connection as many used to do before we integrated it. 

There's several reasons that this decision has been made, but the most relevant and important are:
* As long as we ship LiteLLM we're tied to the common transient dependencies we share and can't update ours freely.
* Due to changes to their API, the way we ran it within our backend had to be changed to a subprocess, which does not work with direct installations of WebUI on Windows.
