### ISSUE TITLE
enh: select model in dropdown with arrow keys

### ISSUE THREAD

**Issue by thearyadev** [open-webui/open-webui#4049]
ability to use the Up/Down arrow keys on the keyboard to navigate the model selection list, triggered by the Enter key. 
_Originally posted by @silentoplayz in https://github.com/open-webui/open-webui/issues/3992#issuecomment-2244170597_

**Comment by silentoplayz** [comment]
> _Originally posted by @silentoplayz in [#3992 (comment)](https://github.com/open-webui/open-webui/pull/3992#issuecomment-2244170597)_

For clarification, and because I used an LLM in attempt to make my original comment clearer, I will mention that I'd like to use the up/down arrow keys on my keyboard to choose which model I want to select with the Enter key on my keyboard. The quoted part before I edited my comment isn't fully clear on this, and appears to almost ask for something else now that I give it another glance.
