### ISSUE TITLE
enh: Enable / Disable indivual OpenAI endpoints

### ISSUE THREAD

**Issue by aaronbolton** [open-webui/open-webui#5119]
**Is your feature request related to a problem? Please describe.**
Feature request, disabling OpenAI API's disables all, I currently have several (OpenAI, Bedrock Proxy & Pipelines)

**Describe the solution you'd like**
I would like to be able to enable or disable individual OpenAI endpoints under Admin Panel>Setting>Connections>OpenAI API

**Describe alternatives you've considered**
disabling all

**Comment by adamoutler** [comment]
I concur. This should be a feature. The only other option is to whitelist each model you wish to use and then logout and login as a user.  This isn't practical. 

There should be a global blacklist.  There are models which are not suitable for any type of use and they should be hidden, even from admins.  For example:
* aybe I decide to create a model and then delete the base model to save space but I want to bring it back later.
* Or maybe I need want to allow use of the latest OpenAI model, but have no use of ChatGPT 1.0.
* Some tools/functions create pipelines which are unusable with certain models and I don't wish to implement whitelisting because it's a development environment.

There are many good reasons to have a way to disable models, not just OpenAI endpoints, but the OpenAI endpoints are most certainly the largest portion of spam in everyone's list.

**Comment by aaronbolton** [comment]
This is exactly why I'm asking I know have such a large list with combination of OpenAI, Bedrock Proxy, Pipelines and now groq

**Comment by tjbck** [comment]
![image](https://github.com/user-attachments/assets/7334fc07-59dd-4407-b1b6-b3cf55287947)


Added to dev! Testing wanted here!

**Comment by aaronbolton** [comment]
Fantastic thank you, the only issues I have found are, but aren't directly related to the functionality of the ability to enable/disable endpoints

1. OpenAI: prefix is removed when using model ID filter
2. Ollama: Prefix doesn't seem to work at all
3. Ollama: The model ID filter doesn't seem to work at all

**Comment by tjbck** [comment]
@aaronbolton try the latest dev, prefix is definitely being applied even with the filter for both openai and ollama, I believe you're confusing the model id, with the model name, which does not contain the prefix id.

**Comment by aaronbolton** [comment]
@tjbck Ah I see, I'm using the latest docker dev container is there any difference? but if I include the prefix yes it works for OpenAI connections

So this work for OpenAI connections
![image](https://github.com/user-attachments/assets/c935103c-0e72-4f2e-9950-a3522f5aa1b2)
![image](https://github.com/user-attachments/assets/85cb84f2-ef20-4542-8ed0-656377c808cd)

For Ollama I've added a prefix but that's not showing
![image](https://github.com/user-attachments/assets/69450cb7-82d7-46b9-8e59-680079cd6662)
![image](https://github.com/user-attachments/assets/5aca702b-5148-4094-94e0-3573db943e9a)

**Comment by aaronbolton** [comment]
@tjbck is there any specific testing or debugging I can do to assist with this?

**Comment by adamoutler** [comment]
I believe we need the whitelist and blacklist in the Workspace rather than on the sources.   The reason I say this is certain functions install pipes on all models, eg. MCTS  or Visual Tree of Thoughts function which duplicates all Ollama models.  These can't be whitelisted on ollama. While I don't mind if users do a MCTS I'd rather they use smaller models.  

I hate to say it, but I don't think this is a good implementation as-is. I mean, it's better than it was, but I think this will always be incomplete without a workspace whitelist and blacklist feature.

**Comment by aaronbolton** [comment]
> I tested and it worked for me. However, this is again, another whitelist.  The blacklist feature is still missing.  In the event there is a new model, I'd like to use it, but because whitelist is the only thing available, I won't know there is a new model available.  
> 
> 
> 
> Eg.  If I whitelist gpt-4o and they release gpt-5 I will never see it.  However i could blacklist all gpt3.5 and others then when a new model drops it will just appear in the list for testing. 

Did the Ollama functions work for you? Such as the prefix and whitelist I've not been able to get these working it works fine for OpenAI connection just not ollama

**Comment by adamoutler** [comment]
> Did the Ollama functions work for you? Such as the prefix and whitelist I've not been able to get these working it works fine for OpenAI connection just not ollama

Yes. Refresh the models list on connections tab and update button next to connection. It renamed all models. 

However it only allows a whitelist which is ok, but only 1/2 of a comprehensive solution.

**Comment by adamoutler** [comment]
Sorry. In the models screen. It will sync the names 

![Screenshot_20241114-184238](https://github.com/user-attachments/assets/5009449f-ee65-4243-a0ec-fe06b626e7b0)

**Comment by adamoutler** [comment]
It's on the models screen. 

![Screenshot_20241114-184238~2](https://github.com/user-attachments/assets/459c2fbb-fba4-4da3-b841-4475427d8ca1)

**Comment by aaronbolton** [comment]
ive tried this and i see the prefix when its updating, but from the drop-down list on the main chat page its not showing

**Comment by adamoutler** [comment]
The drop down box is the name, not the ID.  This changes the ID.
