### ISSUE TITLE
feat: rag api integration support (web search)

### ISSUE THREAD

**Issue by tjbck** [open-webui/open-webui#586]
Extension of #464

> Additional information about web content pipeline, I think we can integrate search api for RAG. Like [serpapi](https://serpapi.com/)(free plan is 100 times search/month), [bing search API](https://www.microsoft.com/en-us/bing/apis/bing-web-search-api) (free plan is 1000 transactions /month),[Wikipedia api](https://api.wikimedia.org/wiki/Searching_for_Wikipedia_articles_using_Python) or other.

**Comment by zinwelzl** [comment]
Hi.

Can you give example how to use it.

I try with 
count words from #http://example.com/
but doesn't work for me

**Comment by tjbck** [comment]
@zinwelzl 

You should start the prompt using the '#' command followed by the website url like such:

<img width="772" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/25473318/f464d276-0f0d-4285-9492-1580adc8900c">

Make sure to click on the button to include the website as a document.

**Comment by ChingWeiChan** [comment]
@tjbck 
 I think we can make the url block clickable (hypertext) or catch the website title then can check the url whether we expected or not.
![截圖 2024-01-30 晚上7 34 52](https://github.com/ollama-webui/ollama-webui/assets/14084937/652828ca-7dc5-42d7-bb45-1895114c1007)

**Comment by tjbck** [comment]
@ChingWeiChan Great idea, I'll make it clickable!

**Comment by tbendien** [comment]
DuckDuckGo search API is free: https://pypi.org/project/duckduckgo-search/

**Comment by dillfrescott** [comment]
Can't wait for this! Super cool stuff!

**Comment by d416** [comment]
Huggingface chat is one of the best implementations of web search I’ve seen for UX so it’d be great if  open-webui used this flow: https://huggingface.co/chat/

HuggingChat also open sourced and is OpenAPI compatible so it can be used with Ollama. The web search can be configured to use different search engines including searxng (private open source search engine) 
https://github.com/huggingface/chat-ui?tab=readme-ov-file#web-search-config

**Comment by strikeoncmputrz** [comment]
[LLM_Web_search](https://github.com/mamei16/LLM_Web_search) is a similar capability implemented in Text Generation WebUI that uses Langchain for RAG. It's worked very well for me and with a good system or character prompt I don't even need to ask it to search the web. https://github.com/mamei16/LLM_Web_search. I made a minor bug fix but otherwise am not affiliated.

**Comment by dillfrescott** [comment]
I think if open webui were to use a search engine, I nominate searxng (running locally) 100%.

I'm using it with another similar project and it works flawlessly and its totally free too, unlike a lot of these API's.

**Comment by sammcj** [comment]
Seconding the recommendation of searxng, it's really very good, self-hostable and works with many backend search engine providers.

**Comment by 9cento** [comment]
+1
Can't wait for a web search feature, game changer!

**Comment by MohamedAliRashad** [comment]
Any updates ?

**Comment by knd775** [comment]
If you don't have anything to add, please don't comment like this. It just makes it harder for other people to follow.

@9cento 
Reactions exist for a reason, use them instead

@MohamedAliRashad 
Do you see any updates?

**Comment by ProjectMoon** [comment]
Idea for how to implement this: make a checkbox/toggle in the message prompt to enable "use web search for enhanced response accuracy". If this toggle is enabled, first send a hidden message to the LLM asking it to analyze the user's message for terms to search for. Then make a search request for each of these terms using some supported search engine, and send the top results to the normal web RAG pipeline.

This would require the admin to configure some search API endpoint. Starting with SearxNG would probably be good because it has an easily configurable JSON API.

**Comment by 9cento** [comment]
> Reactions exist for a reason, use them instead

That was a bump, frustrated mass-replier. And this is another bump.

**Comment by tjbck** [comment]
Implemented in dev.
