### ISSUE TITLE
Requires older versions of Python to run

### ISSUE THREAD

**Issue by yang-gu** [open-webui/open-webui#7429]
# Bug Report

Whenever I enter 

```
pip install --fetch-missing-python open-webui
```
I get a giant dump of failed Python version checks, followed by:

ERROR: Could not find a version that satisfies the requirement open-webui (from versions: none)
ERROR: No matching distribution found for open-webui

---

## Installation Method

pip install, same as in readme

## Environment

- Just vanilla pip install open-webui
- Latest Ollama version
- **Operating System:** Mac OS X, ARM

**Confirmation:**

- [ ] I have read and followed all the instructions provided in the README.md.
- [ ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [ ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

It installs open-webui

## Actual Behavior:

It doesn't install and complains about Python version

## Description

**Bug Summary:**
It doesn't install and complains about Python version

## Reproduction Details

**Steps to Reproduce:**
Whenever I enter 

```
pip install --fetch-missing-python open-webui
```
I get a giant dump of failed Python version checks, followed by:

ERROR: Could not find a version that satisfies the requirement open-webui (from versions: none)
ERROR: No matching distribution found for open-webui

## Logs and Screenshots

<img width="721" alt="image" src="https://github.com/user-attachments/assets/830a09b2-dc83-4453-8f55-461ad4e4c9e2">

<img width="729" alt="image" src="https://github.com/user-attachments/assets/6a310059-532f-40df-8186-9d8b00ec9f96">

**Browser Console Logs:**
None

**Docker Container Logs:**
None

**Screenshots/Screen Recordings (if applicable):**
See above

## Additional Information

I would just like to know how to install.

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Only python 3.11 is supported.

**Comment by yang-gu** [comment]
What do I do then? And why is only 3.11 supported?

**Comment by vnicolici** [comment]
Great. I have two python installations, one is 3.10 on Ubuntu 22.04 in one WSL environment, and one is 3.12 on Ubuntu 24.04 in another WSL environment. Neither work. Unbelievable. I can understand something not being forwards compatible OR not being backwards compatible, but NOT both.

That's why I hate python with a passion. It's sometimes easier to just recode in another language then having to go through the python version dependency hell just to make something work. And yes, I talk from experience: after fighting for a day to get some python code to run, I've rewritten it Go in a couple of hours.

Applications from 1995 (29 years ago) still work on Windows 11 just fine, I just installed Microsoft Money for Windows 95 to prove that:

![image](https://github.com/user-attachments/assets/beee63e3-1d06-4c4e-95c0-3eb4e162259b)

However, open-webui doesn't run on a 3 years old version on python, and doesn't run on a 1 year old version of python either. It need *exactly* the version that is 2 years old. I don't even know what to say about this... I guess it's normal in the python world.
