### ISSUE TITLE
feat: expose rag API

### ISSUE THREAD

**Issue by nick-tonjum** [open-webui/open-webui#774]
I know that the webui has a way to allow passthrough for the Ollama API, so would it be possible to add an extra parameter to - the API to allow users to reference RAG documents or URLs in their call? Of course being handled by the webui before passing it onto Ollama. If I have time I will also help with the coding side of this and submit a PR. 

Thank you!!

**Comment by RWayne93** [comment]
I agree this would be nice. or at least see which chunks the language model referenced for the final output.

**Comment by jnkstr** [comment]
Yes that would be great! Relates to a point in my feature request #715

The metadata such as the filename as `source` and the relevant chunks e.g. texts based on your current question given the LLM in a RAG query as `topk` are already in the rag backend under `/backend/apps/rag/main.py`

You have to send this to the frontend and render this info in order to get this, but backend has the data already!

**Comment by mattfusf** [comment]
Is there any documentation on how to call this?

**Comment by pnmartinez** [comment]
Hello @mattfusf @nick-tonjum 

Apparently the RAG API is now documented on its own on Swagger, see it as the last entry in the docs: https://docs.openwebui.com/features/#-swagger-documentation

The link should be sth like `http://localhost:3000/rag/api/v1/docs`. If I work out something more helpful I'll post back.

**Comment by kw1c-TimoCorstjens** [comment]
Any progress on this?

**Comment by justinh-rahb** [comment]
> Any progress on this?

@kw1c-TimoCorstjens been exposed for months. https://docs.openwebui.com/features#-swagger-documentation
