### ISSUE TITLE
feat: ask user for confirmation when deleting message

### ISSUE THREAD

**Issue by dannyl1u** [open-webui/open-webui#962]
**Is your feature request related to a problem? Please describe.**
Currently, messages can be deleted with a single click, leading to accidental deletions. Since deleting a message also removes all subsequent messages, this can result in significant data loss without the user's intention.

**Describe the solution you'd like**
Reuse the currently implemented UX for confirming deleting entire confirmations.

**Describe alternatives you've considered**
The existing system does not require confirmation before message deletion. While straightforward, this approach lacks safeguards against unintended deletions, highlighting the need for the proposed solution.

**Additional context**
Original delete message PR in https://github.com/open-webui/open-webui/pull/789

**Comment by dannyl1u** [comment]
I'll work on this.

**Comment by taidbui** [comment]
From the latest update, I can confirm that when I deleted a certain message, the subsequent messages were not deleted altogether. Therefore, it would not be an issue. Adding confirmation will make user experience worse because we have to click twice for an action (imagine have to delete a few messages...). Therefore, I suggest to have an option in settings to toggle this rather than imposing as a default feature.

**Comment by dannyl1u** [comment]
@taidbui thanks for letting me know, will log that bug in a separate issue!

**Comment by dannyl1u** [comment]
Closing this feature request as we have decided to not delete all subsequent messages, only the selected prompt/response pair. Thus, a confirmation is not needed at this time
